### ISSUE TITLE
Decoration UIView

### ISSUE THREAD

**Issue by dennismajor1** [RubyCommotion/uikit-dynamics-catalog#10]

**Comment by dennismajor1** [comment]
Hi Will - muffed this a bit between doing a commit on the Github Desktop and then finding that RubyMine was not showing the commit and so did a second commit - so there is an extraneous commit here but the branch looked complete when I checked it. 

Used git push -u origin decoration_view to do the push of the branch

Should have just ignored RubyMine and done the branch push from the command line.

DecorationView complies but it needs to be tested so I will complete AttachmentsViewController which will test one of its features as a start.

I left some commented Objective-C code (properties) for now as a reference - I also left some commented Obj-C code or a TODO where I wasn't a 100% on the conversion (although everything in the file compiles)

Dennis

**Comment by dennismajor1** [comment]
Hi Will,

This is me learning the ropes - so what I'm asking here may or may not make sense...

I'm trying to figure out the correct approach re use of decoration_view - in the Obj-C code 5 VCs import the header for it. I have to review attachments_view, which is one of them, to determine just how it makes use of decoration_view.

We could inject an instance of it into each VC, or make a module of it and included it or make into another base class and then have the 5 VCs subclass it.

Not sure that the last case is an option as decoration_view is a UIView not a UIViewController.

Any thoughts an the best approach?

**Comment by willrax** [comment]
@dennismajor1 no problem with the first one.

In the storyboard they change the `UIView` class to the `DecorationView` so we can just do the same but directly in the controller.

```
class DecorationView < UIView
end
```

Then in the attachments view controller specify the view with:

```
def loadView
  self.view = DecorationView.alloc.init
end
```
