### ISSUE TITLE
dennis_development

### ISSUE THREAD

**Issue by dennismajor1** [RubyCommotion/uikit-dynamics-catalog#14]
Will, luri,

I'm going to go with one branch (dennis_development) and do all my work here - my other branches decoration_view, continuous_push_view and attachments_view can be deleted or I can delete them.

I'm going to focus on one branch - currently I working on the AttachmentsViewController and have the subViews converted from IB into code - next comes the more important step of making the VC work as it is suppose to :-)

I'll just keep building out any VCs that I see haven't been completed or that you fellas are not presently working on.

**Comment by willrax** [comment]
Hey Dennis, sounds good. I'll hopefully get a few more done this weekend.

**Comment by dennismajor1** [comment]
Removed all my branches and set master as default on github repo - somehow in my thrashing around I had set attachments_view as default.
