### ISSUE TITLE
Add Spec Tests

### ISSUE THREAD

**Issue by dennismajor1** [RubyCommotion/uikit-dynamics-catalog#17]
Add or build on existing spec tests for all VCs. As needed, refactor VCs to allow unit tests.
- continuous and instantaneous VC unit tests completed.

**Comment by dennismajor1** [comment]
Will - thought I'd run spec tests for full app before adding any additional tests and I came across a failure that doesn't make sense to me but might to you.

The main_spec.rb failed for test of one window - to make it pass required the following:

@app.windows.size.should == 3

Does it make sense to you that there would be 3 windows - anything I've read says there normally is just one.

I reset the simulator and did a rake clean --all and still the test says there are three windows??

**Comment by willrax** [comment]
Yeah that shouldn't be the case. The tests are a bit weird at the moment.

**Comment by dennismajor1** [comment]
Hi Will,
Question for you - is there a reason you seem to avoid using MacBacon's `tests controller` method. For example:

``` ruby
describe "AttachmentsView' view" do
  tests AttachmentsView

  # Add your specifications here.
end
```

Why not use `tests controller` instead of this approach:

``` ruby
before do
    @subject = AttachmentsView.new
  end
```

The `tests controller` method would, I think, make the tests a little cleaner and less verbose.

Trying to understand why you haven't used it and as well - do you have any concerns if I refactor some of the controller specs to make use of it e.g. AttachmentsView

Here's RubyMotion reference link:

http://www.rubymotion.com/developer-center/articles/testing/#_views_and_controllers_testing 

Dennis

**Comment by willrax** [comment]
No reason. I was using promotion as a reference so must have picked it up there. I didn't realise that existed. I'm all for using whatever conventions MacBacon has. :)

**Comment by dennismajor1** [comment]
Great - thanks for the quick reply Will.

**Comment by dennismajor1** [comment]
Spec test for DecorationView crashes - investigating. 

Since DecorationView subclasses UIView I suspect that the `tests DecorationView` cannot be used since this class is not a controller class and I think this is possibly where the `before` block with an `@subject` pointing to the instantiated view object should be applied. Going to try this as a solution. 

Multiple windws causing AppDelegate test for one window to fail as there are 6 at the time the test happens.

If you artificially change the name of the AppDelegate spec test file so it runs first then the test passes. So it seems to be a case of the MacBacon window and controller objects needing to be released at the end of each spec file run via and after block - so far attempts to do this have not worked - investigating.

**Comment by dennismajor1** [comment]
_Spec test for DecorationView crashes - investigating_ ==>> Problem fixed - used `Before` block to create instance (`@view`) of `DecorationView` as `UIView` and then removed `tests <controller>`

**Comment by dennismajor1** [comment]
Basic spec tests completed for all VC's
