### ISSUE TITLE
Gravity Spring View Controller

### ISSUE THREAD

**Issue by willrax** [RubyCommotion/uikit-dynamics-catalog#2]

**Comment by willrax** [comment]
I'll get this one done.

**Comment by dennismajor1** [comment]
Hi Will - going to start on converting this one and get tests up to a basic level for all VCs and then I suggest we publish as an available RM version of UIDynamicCatalog on google groups RubyMotion.

**Comment by willrax** [comment]
Hey Dennis,

Apologies. Been extremely busy at work and home. I've got a few days off now and would like to get this done. Have you started?

**Comment by dennismajor1** [comment]
Just pulled in the obj-c and haven't done more that look at the code. You can go ahead Will and complete this one  - looks like it a re-hash of attachment view but with some gravity behaviour thrown in.

I'll look at doing more tests on any of the VCs that still need some.

**Comment by willrax** [comment]
Almost done. Getting some error when trying to create the dashes. Cannot create float from nil. Any ideas @dennismajor1? I'm sure i'm just missing something obvious.

**Comment by willrax** [comment]
relevant code: https://github.com/RubyCommotion/uikit-dynamics-catalog/blob/gravity-view/app/controllers/gravity_spring_controller.rb

**Comment by dennismajor1** [comment]
Hi Will - I'll take a look and see if I can help.

**Comment by dennismajor1** [comment]
Will - I tried it - uncommented the code to create dashes and it seems to work - now what I did was copied your code into my existing clone of the master created a branch and then created your gravity spring file by coping and pasting your code from your GitHub branch.

Much earlier I had to modify trackAndDrawAttachmentFromView in DecorationView to get it to play nice (I think - going by memory). So ... I my guess is if you take a clone of the master that is up there now and then add your file for spring gravity to it - it'll work.

**Comment by dennismajor1** [comment]
Will - now that all dynamic controllers are finished I hope to finish the unit tests for each of them and then tune up the README.

Finally, I plan post a notice on RubyMotion groups that the catalog is available to anyone looking for RM example code.

Is this OK with you?

**Comment by willrax** [comment]
Very strange. I thought I had cut a branch from master last night. Anyway that's great! Just pushed the controller to master. I think a notice on the mailing list is a great idea. What did you want to put in the Readme?

**Comment by willrax** [comment]
see #26
