### ISSUE TITLE
Continuous Push View Controller

### ISSUE THREAD

**Issue by willrax** [RubyCommotion/uikit-dynamics-catalog#4]

**Comment by dennismajor1** [comment]
Will - I'd like to get the VCs that use the decoration_view converted - will help knowing that any changes I make there work as expected - is it OK if I convert the Continuous Push View Controller?

**Comment by willrax** [comment]
Go for it. I think @iurimatias is doing the pendulum one.

**Comment by dennismajor1** [comment]
OK - thanks.

On Saturday, 22 February 2014, Will Raxworthy notifications@github.com
wrote:

> Go for it. I think @iurimatias https://github.com/iurimatias is doing
> the pendulum one.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RubyCommotion/uikit-dynamics-catalog/issues/4#issuecomment-35823524
> .

## 

Sent from Gmail Mobile

**Comment by dennismajor1** [comment]
Going to do a raw conversion with tests and then iteratively Rubify it.

**Comment by dennismajor1** [comment]
Missed @iurimatias  doing pendulum - should I be tracking IRC or twitter?

**Comment by willrax** [comment]
Oh. I just noticed he assigned the task to himself. :)

**Comment by dennismajor1** [comment]
OK thanks Will - I must have missed it in the issues - just trying not to do what someone else is already working on :-)

**Comment by dennismajor1** [comment]
Starting on completion of Continuous Push View Controller

**Comment by dennismajor1** [comment]
Merged continuous push to master locally and 'tested OK'. Pushed local master to origin/master
