### ISSUE TITLE
Custom Dynamic Item View Controller

### ISSUE THREAD

**Issue by willrax** [RubyCommotion/uikit-dynamics-catalog#7]

**Comment by willrax** [comment]
I'm going to get started on this one.

**Comment by dennismajor1** [comment]
Hi Will - how be I take this feature and complete it and leave you with Gravity Spring.

**Comment by willrax** [comment]
Did you mean to close this one?

**Comment by willrax** [comment]
Sounds like a plan. Didn't realise I had tagged two issues.

**Comment by dennismajor1** [comment]
No Will I didn't - I hit comment & close instead of comment only - sorry -
I should have re-opened.

**Comment by willrax** [comment]
No problem. I figured that was the case. There really needs to be a confirm dialog on that button. We always do it at work. haha

**Comment by dennismajor1** [comment]
Custom Dynamic Item View Controller has been completed.
